# Generated by Django 2.2 on 2022-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='站点名称')),
                ('blog_title', models.CharField(max_length=50, verbose_name='首页标题')),
                ('url', models.URLField(verbose_name='站点网址')),
                ('background', models.URLField(verbose_name='背景图片')),
                ('image', models.URLField(verbose_name='头像链接')),
                ('author', models.CharField(max_length=50, verbose_name='作者名称')),
                ('ICP', models.CharField(max_length=20, verbose_name='ICP备案号')),
                ('copyright', models.CharField(max_length=20, verbose_name='版权')),
                ('visitors', models.IntegerField(default=0, verbose_name='访客数')),
                ('views', models.IntegerField(default=0, verbose_name='访问量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
                'db_table': 'tb_site_info',
            },
        ),
    ]
